name: niggatrader
description: A classic iOS style trading journal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shadcn_flutter: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/nq.png
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
        - asset: fonts/SF-Pro-Text-Medium.otf
          weight: 500
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
